const data = [
  {
    id: 1,
    name: 'Hikayen',
    postName: 'ozge.cey',
    image: require('../images/profil.jpg'),
    postImage: require('../images/portakal.jpg'),
    like: 25,
    comment: '4 yorumun tümünü gör',
    explanation: 'Hiçbir şey gözüktüğü gibi değildir...',
    time: '1 saat önce',
    timeStory: '1s',
    islike: false,
  },
  {
    id: 2,
    name: 'macellan',
    postName: 'macellan',
    image: require('../images/macellan.jpg'),
    postImage: require('../images/fintech.jpeg'),
    like: 360,
    comment: '4 yorumun tümünü gör',
    explanation: 'Beklemede kalın',
    time: '2 saat önce',
    timeStory: '53d',
    islike: false,
  },
  {
    id: 3,
    name: 'ezgiceylan',
    postName: 'ezgiceylan',
    image: require('../images/ezgiceylan.jpeg'),
    postImage: require('../images/oje.jpg'),
    like: 120,
    comment: '4 yorumun tümünü gör',
    explanation: 'Yeni tırnaklarım:)',
    time: '3 saat önce',
    timeStory: '2s',
    islike: false,
  },
  {
    id: 4,
    name: 'catvideos',
    postName: 'catvideos',
    image: require('../images/cat.jpg'),
    postImage: require('../images/catPost.jpg'),
    like: 160,
    comment: '8 yorumun tümünü gör',
    explanation: 'Öfkeli bir kedi',
    time: '5 saat önce',
    timeStory: '3s',
    islike: false,
  },
  {
    id: 5,
    name: 'alternatif',
    postName: 'alternatifSuperApp',
    image: require('../images/alternatif.png'),
    postImage: require('../images/Afiş.png'),
    like: 220,
    comment: '110 yorumun tümünü gör',
    explanation: 'Beklemede kalın',
    time: '8 saat önce',
    timeStory: '6s',
    islike: false,
  },
  {
    id: 6,
    name: 'bfy',
    postName: 'bfy',
    image: require('../images/bfy.png'),
    postImage: require('../images/bfyPost.jpg'),
    like: 150,
    comment: '25 yorumun tümünü gör',
    explanation: 'Araç takip hiç bu kadar kolay olmamıştı',
    time: '24 saat önce',
    timeStory: '24s',
    islike: false,
  },
];
export default data;
