import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  userName: {
    color: '#D8D8D8',
    fontWeight: 'bold',
    marginTop: 3,
    marginBottom: 3,
    fontSize: 16,
    marginLeft: 10,
  },
  bio: {
    color: '#D8D8D8',
    fontSize: 15,
    marginLeft: 12,
    marginTop: 5,
  },
  bioContainer: {
    marginVertical: 5,
    marginHorizontal: 5,
  },
  edit: {
    height: 35,
    borderRadius: 10,
    backgroundColor: '#262626',
    justifyContent: 'center',
    marginVertical: 5,
    marginBottom: 20,
    marginLeft: 15,
    marginRight: 10,
    alignItems: 'center',
    width: '82%',
  },
  editText: {
    color: '#D8D8D8',
    fontWeight: 'bold',
    fontSize: 16,
  },
  icon: {
    height: 36,
    borderRadius: 10,
    backgroundColor: '#262626',
    width: '10%',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
    marginVertical: 5,
  },
  body: {
    marginBottom: 20,
  },
  container: {
    width: 75,
    height: 75,
    backgroundColor: 'black',
    borderWidth: 1.5,
    borderRadius: 100,
    borderColor: '#2E2E2E',
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    width: '90%',
    height: '90%',
    borderRadius: 100,
    borderWidth: 0.8,
    borderColor: '#2E2E2E',
  },
  label: {
    color: 'white',
    marginTop: 5,
  },
  bodyProfile: {
    height: '7%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  left: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '43%',
    justifyContent: 'space-around',
  },
  right: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: '22%',
  },
  header: {
    color: 'white',
    fontWeight: '400',
    fontSize: 22,
  },
  icons: {
    width: 28,
    height: 28,
  },
  line: {
    borderBottomWidth: 0.8,
    borderBottomColor: '#3a3a3a',
    marginTop: 10,
  },
  sheet: {
    backgroundColor: '#262626',
    margin: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  sheet2: {
    backgroundColor: '#262626',
    marginBottom: 30,
    flexDirection: 'row',
    alignItems: 'center',
  },
  labelText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '500',
    paddingLeft: 15,
  },
  container2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  image2: {
    height: 80,
    width: 80,
    borderRadius: 100,
    marginLeft: 5,
  },
  numbers: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '73%',
    alignItems: 'center',
    marginHorizontal: 5,
  },
  numberContainer: {
    color: 'white',
    fontWeight: 'bold',
    alignSelf: 'center',
    fontSize: 18,
    marginBottom: 5,
  },

  text: {
    color: 'white',
    fontSize: 16,
    alignSelf: 'center',
  },
});
