const data3 = [
  {
    video: require('../storage/videos/reels1.mp4'),
    image: require('../storage/images/profil.jpg'),
    user: 'ezgiceylan',
    explanation: 'The memory..',
    likes: 852,
    comment: '35',
    isLike: false,
    follow: true,
  },
  {
    video: require('../storage/videos/reels2.mp4'),
    image: require('../storage/images/profil5.jpg'),
    user: 'guneys',
    explanation: 'Arkadaşlarımı çok seviyorum <3',
    likes: 25,
    comment: '14',
    isLike: false,
    follow: true,
  },
  {
    video: require('../storage/videos/reels3.mp4'),
    image: require('../storage/images/cat.jpg'),
    user: 'funnycats',
    explanation: 'Günaydııınnnn',
    comment: 5,
    likes: 134,
    isLike: false,
    follow: true,
  },
  {
    video: require('../storage/videos/reels4.mp4'),
    image: require('../storage/images/ezgiceylan.jpeg'),
    user: 'theart',
    explanation: 'Harika bir haftasonu!',
    likes: 184,
    comment: '3',
    isLike: false,
    follow: true,
  },
  {
    video: require('../storage/videos/reels5.mp4'),
    image: require('../storage/images/profil6.jpg'),
    user: 'sinemm',
    explanation: 'New phone',
    comment: 55,
    likes: 184,
    isLike: false,
    follow: true,
  },
  {
    video: require('../storage/videos/reels6.mp4'),
    image: require('../storage/images/profil3.jpg'),
    user: 'theart',
    explanation: 'Bu vr harika dostum..',
    likes: 124,
    comment: '96',
    isLike: false,
    follow: true,
  },
];
export default data3;
